### ISSUE TITLE
RTL extension

### ISSUE THREAD

**Issue by perpi** [samymassoud/flarum-arabic#2]
Hey there
Here is a quote: 'it can be used with any RTL language';
So, how can we use just the rtl & Does it activate Arabic on our forum?!

**Comment by samymassoud** [comment]
Hello perpi,i have a plan to make two separate extensions one for RTL and other for Arabic.
Right now i don't have too much time to do it,so if you know development you should use RTL part out from my current Extension, and if not please wait me to release it out.
Thanks

**Comment by perpi** [comment]
Hey man, 1st of all, I should say a big thanks for supporting RTL.

I will wait for your work. I don't have any experience with codes.

**Comment by onrea** [comment]
Me too, I'll appreciate that if you separate them.

**Comment by perpi** [comment]
Any News?!

**Comment by samymassoud** [comment]
i'm too busy working on my projects, once i have some free time i will create it

**Comment by samymassoud** [comment]
It's now available

https://discuss.flarum.org/d/2484-flarum-rtl-extension

https://github.com/samymassoud/flarum-ext-rtl

**Comment by perpi** [comment]
Wow, thank you man.
